# Nineteen eighty four novel data.
nineteen-eighty-four:
    author: George Orwell
    published-at: 1949-06-08
    page-count: 328
    description: |
        A Novel, often published as 1984, is a dystopian novel by English novelist George Orwell.
        It was published in June 1949 by Secker & Warburg as Orwell's ninth and final book.



# The above code will translate to JSON as:
# {
#      "nineteen-eighty-four": {
#          "author": "George Orwell",
#          "published-at": "1949-06-08T00:00:00.000Z",
#          "page-count": 328,
#          "description": "A Novel, often published as 1984, is a dystopian novel by English novelist George Orwell.\nIt was published in June 1949 by Secker & Warburg as Orwell's ninth and final book.\n"
#       }
# }